export const adminAuditResourceOptions = {
  navigation: { name: '统计与审计', icon: 'Shield' },
  label: '操作审计',
  listProperties: [
    'id',
    'createdAt',
    'actor',
    'action',
    'resource',
    'recordId',
    'ip',
  ],
  showProperties: [
    'id',
    'createdAt',
    'actor',
    'action',
    'resource',
    'recordId',
    'fromStatus',
    'toStatus',
    'requestId',
    'ip',
    'userAgent',
    'detail',
  ],
  filterProperties: [
    'createdAt',
    'actor',
    'action',
    'resource',
    'recordId',
    'requestId',
    'ip',
  ],
  actions: {
    // Audit logs are append-only.
    new: { isVisible: false, isAccessible: false },
    edit: { isVisible: false, isAccessible: false },
    delete: { isVisible: false, isAccessible: false },
    bulkDelete: { isVisible: false, isAccessible: false },
  },
  properties: {
    createdAt: { label: '创建时间' },
    actor: { label: '操作者' },
    action: { label: '动作' },
    resource: { label: '资源' },
    recordId: { label: '记录 ID' },
    fromStatus: { label: '变更前状态' },
    toStatus: { label: '变更后状态' },
    requestId: { label: '请求 ID' },
    ip: { label: '来源 IP' },
    userAgent: { label: '用户代理' },
    detail: {
      label: '详情',
      type: 'mixed',
      isVisible: { list: false, show: true, edit: false, filter: false },
    },
  },
} as const;
