export const requestLogResourceOptions = {
  navigation: { name: '统计与审计', icon: 'BarChart2' },
  label: '请求日志',
  listProperties: [
    'id',
    'createdAt',
    'method',
    'route',
    'status',
    'durationMs',
    'ip',
  ],
  showProperties: [
    'id',
    'createdAt',
    'requestId',
    'method',
    'route',
    'url',
    'status',
    'durationMs',
    'ip',
    'userAgent',
    'sampleRate',
  ],
  filterProperties: [
    'createdAt',
    'method',
    'route',
    'status',
    'requestId',
    'ip',
  ],
  actions: {
    // Request logs are append-only and may be cleaned up by retention.
    new: { isVisible: false },
    edit: { isVisible: false },
    delete: { isVisible: false },
    bulkDelete: { isVisible: false },
  },
  properties: {
    createdAt: { label: '创建时间' },
    requestId: { label: '请求 ID' },
    method: { label: '方法' },
    route: { label: '路由' },
    url: { label: 'URL' },
    status: { label: '状态码' },
    durationMs: { label: '耗时(ms)' },
    ip: { label: '来源 IP' },
    userAgent: { label: '用户代理' },
    sampleRate: { label: '采样率' },
  },
} as const;
